name: Java CI - Run All Tests
 
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Clonar Repositorio en el Entorno de Ejecucion
      - uses: actions/checkout@v3
 
      # Configurar Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Descargar JUnit
      - name: Descargar JUnit
        run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
 
      # Compilar Archivos Java (src y test)
      - name: Compilar codigo
        run: |
          mkdir -p out
          javac -cp junit-platform-console-standalone-1.9.3.jar -d out $(find src test -name "*.java")
 
      # Ejecutar los tests
      - name: Ejecutar tests
        run: |
          java -jar junit-platform-console-standalone-1.9.3.jar --class-path out --scan-classpath
